### PR TITLE
PMM-12219 support special characters in password.

### LINKED ISSUE #948: nil pointer during url parsing
**Describe the bug**
When starting the exporter (from version 0.42.0 on) and providing a password that contains special characters the exporter crashes during the call here:
https://github.com/percona/mongodb_exporter/blob/v0.42.0/main.go#L147

Using an older version (e.g. 0.41.0) with the same arguments results in an error that logs the mongodb connection string.

Are passwords with special characters even supported? 

**To Reproduce**

($PASSWORDS contains special characters, in my tests I used ? and !)

1. Start the exporter with the following arguments: mongodb_exporter  --mongodb.uri "mongodb://localhost:27017/?authSource=admin" --mongodb.user $USER --mongodb.password $PASSWORD
2. The exporter crashes pretty much immediately

**Expected behavior**
I expect it not to crash.

**Logs**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xcea293]
goroutine 1 [running]:
net/url.(*URL).Port(...)
   /opt/bitnami/go/src/net/url/url.go:1196
main.buildExporter({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0006026f0, 0x1, ...}, ...}, ...)
   /bitnami/blacksmith-sandox/mongodb-exporter-0.42.0/src/github.com/percona/mongodb_exporter/main.go:147 +0xd3
main.buildServers({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc0006026f0, 0x1, ...}, ...}, ...)
   /bitnami/blacksmith-sandox/mongodb-exporter-0.42.0/src/github.com/percona/mongodb_exporter/main.go:197 +0x105
main.main()
   /bitnami/blacksmith-sandox/mongodb-exporter-0.42.0/src/github.com/percona/mongodb_exporter/main.go:138 +0x725

**Environment**
 - environment: k8s
 - exporter version: 0.42.0

**Additional context**
-

### PR DESCRIPTION
**Pull request by BupycHuk**
[PMM-12219](https://jira.percona.com/browse/PMM-12219) (optional, if ticket reported)

- [ ] Links to related pull requests (optional).
- fixes #948 

---

Below we provide a basic checklist of things that would make it a good PR:
- Make sure to sign the CLA (Contributor License Agreement).
- Make sure all tests pass.
- Keep current with the target branch and fix conflicts if necessary.
- Update jira ticket description if necessary.
- Attach screenshots and/or console output to the jira ticket to confirm new behavior, if applicable.
- Leave notes to the reviewers if you need to focus their attention on something specific.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com).

[PMM-12219]: https://perconadev.atlassian.net/browse/PMM-12219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -219,12 +219,21 @@ func TestBuildURI(t *testing.T) {
...
-		newUri := buildURI(tc.origin, tc.newUser, tc.newPassword)
-		// t.Logf("Origin: %s", tc.origin)
-		// t.Logf("Expect: %s", tc.expect)
-		// t.Logf("Result: %s", newUri)
-		assert.Equal(t, newUri, tc.expect)
+		t.Run(tc.situation, func(t *testing.T) {
+			newURI := buildURI(tc.origin, tc.newUser, tc.newPassword, logrus.New())
+			// t.Logf("Origin: %s", tc.origin)
+			// t.Logf("Expect: %s", tc.expect)
+			// t.Logf("Result: %s", newURI)
```
Comment (JiriCtvrtka) [inline main_test.go:235]: Do we need this?

**Review by JiriCtvrtka — APPROVED** [review]

File: main_test.go (hunk 1 above)
Comment (BupycHuk) [reply main_test.go:235]: Actually not, but it was there, so I didn't touch it. let me remove
```suggestion
```

**Review by idoqo — APPROVED** [review]
