### PR TITLE
PMM-13426: Fix PBM collector memory leak

### LINKED ISSUE #922: 0.41.1 Connections didn't closed
**Describe the bug**
New exporter doesn't close connections and open files(fs-max) will be reached

**To Reproduce**
1. Install `mongodb_exporter` 0.41.1
2. Run `while true; do echo $(date -u +"%Y-%m-%d %H:%M:%S") $(sudo lsof -p $(pgrep -f mongodb_exporter) | wc -l); sleep 5; done` and you will see increases over all time

**Expected behavior**
Stable connection count.

**Logs**
No available extra logs

**Environment**
 - OS, Debian 11
 - environment (docker, k8s, etc)
 - MongoDB version 6.0.6

### PR DESCRIPTION
**Pull request by idoqo**
[PMM-13426](https://perconadev.atlassian.net/browse/PMM-13426) (optional, if ticket reported)

- [ ] https://github.com/Percona-Lab/pmm-submodules/pull/3728/

Closes #922 and #924 

---

Below we provide a basic checklist of things that would make it a good PR:
- Make sure to sign the CLA (Contributor License Agreement).
- Make sure all tests pass.
- Keep current with the target branch and fix conflicts if necessary.
- Update jira ticket description if necessary.
- Attach screenshots and/or console output to the jira ticket to confirm new behavior, if applicable.
- Leave notes to the reviewers if you need to focus their attention on something specific.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com).

[PMM-13426]: https://perconadev.atlassian.net/browse/PMM-13426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: exporter/exporter.go [hunk 1]
```diff
@@ -249,8 +249,14 @@ func (e *Exporter) makeRegistry(ctx context.Context, client *mongo.Client, topol
...
-		pbmc := newPbmCollector(ctx, client, e.opts.URI, e.opts.Logger)
-		registry.MustRegister(pbmc)
+		pbmc, err := newPbmCollector(ctx, client, e.opts.URI, e.opts.Logger)
+		if err != nil {
+			e.logger.Errorf("Cannot create PBM collector: %v, collector will now be disabled.", err)
+			e.opts.EnablePBMMetrics = false
+			requestOpts.EnablePBMMetrics = false
+		} else {
+			registry.MustRegister(pbmc)
+		}
```
Comment (BupycHuk) [inline exporter/exporter.go:259]: we create these objects on each request, so it won't help much

File: exporter/pbm_collector.go [hunk 2]
```diff
@@ -53,17 +53,34 @@ func createPBMMetric(name, help string, value float64, labels map[string]string)
...
+	if err != nil {
+		logger.Errorf("failed to get PBM configuration during initialization: %s", err.Error())
+		return nil, err
+	}
 	return &pbmCollector{
 		ctx:      ctx,
 		mongoURI: mongoURI,
 		base:     newBaseCollector(client, logger.WithFields(logrus.Fields{"collector": "pbm"})),
-	}
+	}, nil
```
Comment (BupycHuk) [inline exporter/pbm_collector.go:83]: let's revert it because of message above

File: exporter/pbm_collector.go [hunk 3]
```diff
@@ -112,7 +95,7 @@ func (p *pbmCollector) collect(ch chan<- prometheus.Metric) {
 
 	pbmConfig, err := pbmClient.GetConfig(p.ctx)
 	if err != nil {
-		logger.Errorf("failed to get PBM configuration: %s", err.Error())
+		logger.Warnf("failed to get PBM configuration: %s", err.Error())
```
Comment (BupycHuk) [inline exporter/pbm_collector.go:98]: I think it should be Info level if we expect that pbm config might not exist there

**Review by JiriCtvrtka — APPROVED** [review]
